apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: keycloak-
  annotations:
    olm.providedAPIs: 'Keycloak.v2alpha1.k8s.keycloak.org,KeycloakRealmImport.v2alpha1.k8s.keycloak.org'
    argocd.argoproj.io/sync-wave: "0"
  name: keycloak-g42cv
  namespace: keycloak
spec:
  targetNamespaces:
    - keycloak
  upgradeStrategy: Default