apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: cluster-keyclock
  namespace: rhacm-hub
spec:
  clusterSelector:
    matchExpressions:
      - key: spoke-gitops
        operator: In
        values:
          - "true"
